'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Delta_ERP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property AppIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AppIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property APTIV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("APTIV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_right_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_front_open_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_front_open_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_front_open_hand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_front_open_hand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_open_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_open_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property critical_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("critical_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property critical_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("critical_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_package_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_package_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excel_exports_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel_exports_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greater_equal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greater_equal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property information_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property information_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minor_equal_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minor_equal_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property No_image_available() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_image_available", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property not_equal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("not_equal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .auto-style2 {
        '''            color: #FFFFFF;
        '''            font-weight: bold;
        '''            background-color: #006699;
        '''        }
        '''    &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;h1 style=&quot;color: #5e9ca0;&quot;&gt;Mover de muestras&amp;nbsp;&lt;span style=&quot;color: #2b2301;&quot;&gt;@id&lt;/span&gt; aprobado.&lt;/h1&gt;
        '''&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;Detalles:&lt;/h2&gt;
        '''&lt;p&gt;&lt;strong&gt;Usuario:&lt;/strong&gt; @use [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ORD_MoverEmailTemplate() As String
            Get
                Return ResourceManager.GetString("ORD_MoverEmailTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date] AS DeliveryDate,CASE WHEN DATEPART(WEEKDAY,SC.Date) IN ({0},{1}) THEN 0 ELSE FLOOR(ISNULL(OpenQuantity,0)/{2}) END AS OpenQuantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board LEFT OUTER JOIN vw_Sch_WeeklyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Week] = CR.[Week] 
        '''WHERE ((&apos;{3}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_AverageRequirementsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_AverageRequirementsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date] AS DeliveryDate,CASE WHEN DATEPART(WEEKDAY,SC.Date) IN ({0},{1}) THEN 0 ELSE FLOOR(ISNULL(OpenQuantity,0)/{2}) END AS OpenQuantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board LEFT OUTER JOIN vw_Sch_WeeklyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Week] = CR.[Week] 
        '''INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''WHE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_AverageRequirementsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_AverageRequirementsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(SC.WorkingShifts,&apos;&apos;) AS DayShifts,B.ShiftCombination AS BoardShifts,CL.Seconds
        '''FROM Sys_Calendar AS SC
        '''LEFT OUTER JOIN Sys_ShiftCombination AS SF ON SC.WorkingShifts = SF.Combination
        '''CROSS JOIN Sch_Materials AS M  
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material
        '''INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board
        '''INNER JOIN Eng_1719Controls AS CL ON M.Material = CL.Material
        '''INNER JOIN Sys_ShiftCombination AS SFB ON B.ShiftCombination = SFB.Comb [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_BoardCapacitiesByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_BoardCapacitiesByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(SC.WorkingShifts,&apos;&apos;) AS DayShifts,Bd.ShiftCombination AS BoardShifts,CL.Seconds
        '''FROM Sys_Calendar AS SC
        '''LEFT OUTER JOIN Sys_ShiftCombination AS SF ON SC.WorkingShifts = SF.Combination
        '''CROSS JOIN Sch_Materials AS M  
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material
        '''INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board
        '''INNER JOIN Eng_1719Controls AS CL ON M.Material = CL.Material
        '''INNER JOIN Sys_ShiftCombination AS SFB ON Bd.ShiftCombination = SFB. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_BoardCapacitiesByFamily() As String
            Get
                Return ResourceManager.GetString("PP_BoardCapacitiesByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,SC.[Date],DATENAME(W,SC.[Date]) AS WeekDay,ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND M.Business = &apos;{2}&apos; 
        '''AND ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1} [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_ByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_ByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,SC.[Date],DATENAME(W,SC.[Date]) AS WeekDay,ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND B.Family = &apos;{2}&apos; 
        '''AND ((&apos; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_ByFamily() As String
            Get
                Return ResourceManager.GetString("PP_ByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,C.Comment 
        '''FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board INNER JOIN Sch_DailyProductionPlanComments AS C ON M.Material = C.Material AND MB.Board = C.Board WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction))
        '''AND M.Business = &apos;{2}&apos; AND B.Volume=&apos;Low&apos; ORDER BY M.Material.
        '''</summary>
        Friend ReadOnly Property PP_CommentsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_CommentsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,C.Comment 
        '''FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_DailyProductionPlanComments AS C ON M.Material = C.Material AND MB.Board = C.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction))
        '''AND B.Family = &apos;{2}&apos; AND Bd.Volume=&apos;Low&apos; 
        '''ORDER BY M.Material.
        '''</summary>
        Friend ReadOnly Property PP_CommentsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_CommentsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,Bd.Board,SC.[Date],DATENAME(W,SC.[Date]) AS WeekDay,ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS Bd ON M.Material = Bd.Material 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; 
        '''AND ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction))
        '''ORDER BY M.Material,SC.[Date].
        '''</summary>
        Friend ReadOnly Property PP_Daily_Plant() As String
            Get
                Return ResourceManager.GetString("PP_Daily_Plant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board 
        '''LEFT OUTER JOIN vw_Sch_EPSDailyProduction AS DP ON M.Material = DP.Material AND SC.[Date] = DP.[Date]
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) AND SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND M.Business = &apos;{2} [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_EPSProductionByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_EPSProductionByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(Quantity,0) AS Quantity  
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''LEFT OUTER JOIN vw_Sch_EPSDailyProduction AS DP ON M.Material = DP.Material AND SC.[Date] = DP.[Date] 
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_EPSProductionByFamily() As String
            Get
                Return ResourceManager.GetString("PP_EPSProductionByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,Bd.Class AS Tool, Bd.Volume,Bd.ShiftCombination,Seconds,Operators,M.CustomerPN,M.Description,B.Family,M.Business,StdPack,ISNULL(PastDue,0) AS PastDue,ISNULL(CI.Quantity,0) AS Stock,StartProduction,EndProduction FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board  INNER JOIN Eng_1719Controls AS Cl ON M.Material = Cl.Material INNER JOIN Sch_Business AS B ON M.Business = B.Business LEFT OUT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_MaterialsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_MaterialsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,Bd.Class AS Tool,BD.Volume,Bd.ShiftCombination,Seconds,Operators,M.CustomerPN,M.Description,B.Family,M.Business,StdPack,ISNULL(PastDue,0) AS PastDue,ISNULL(CI.Quantity,0) AS Stock,StartProduction,EndProduction FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board  INNER JOIN Eng_1719Controls AS Cl ON M.Material = Cl.Material INNER JOIN Sch_Business AS B ON M.Business = B.Business LEFT OUTE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_MaterialsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_MaterialsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date] AS DeliveryDate,ISNULL(OpenQuantity,0) AS OpenQuantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board LEFT OUTER JOIN vw_Sch_DailyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Date] = CR.DeliveryDate
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) AND SC.[Date] BETWEEN &apos;{ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_RequirementsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_RequirementsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,Bd.Board,SC.[Date] AS DeliveryDate,ISNULL(OpenQuantity,0) AS OpenQuantity  
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''LEFT OUTER JOIN vw_Sch_DailyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Date] = CR.DeliveryDate 
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_RequirementsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_RequirementsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,Bd.Board,[Week],ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS Bd ON M.Material = Bd.Material INNER JOIN Mfg_Boards AS Mb ON Bd.Board = Mb.Board 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) AND MB.Volume=&apos;Low&apos;         ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_Weekly_Plant() As String
            Get
                Return ResourceManager.GetString("PP_Weekly_Plant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_blue_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_blue_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_list_bullets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_bullets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_light_blue_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_light_blue_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_red_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_red_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT0,160^A0N,140,140^FH\^FB1200,1,0,C,1^FD*** CRITICO ***^FS
        '''^FT0,340^A0N,200,200^FH\^FB1200,1,0,C,1^FD@partnumber^FS
        '''^FT0,410^A0N,60,60^FH\^FB1200,1,0,L,1^FDUsuario: @user^FS
        '''^FT0,470^A0N,60,60^FH\^FB1200,1,0,L,1^FDArea: @area^FS
        '''^FT0,590^A0N,60,60^FH\^FB1200,2,0,L,1^FDComentario: @comment^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_CriticalLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_CriticalLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT350,120^A0N,90,90^FH\^FB800,1,0,R,1^FDMover ID @moverid^FS
        '''^FT0,340^A0N,200,200^FH\^FB1200,1,0,C,1^FD@partnumber^FS
        '''^FT20,430^A0N,80,80^FH\^FB1200,1,0,L,1^FDCantidad: @quantity @uom^FS
        '''^FT20,490^A0N,60,60^FH\^FB1200,1,0,L,1^FDLocal: @local^FS
        '''^BY4,4,104^FT20,150^BCN,,Y,N^FD@partid^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_MoverLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_MoverLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT0,160^A0N,140,100^FH\^FB1200,1,0,C,1^FD***ALERTA DE CALIDAD***^FS
        '''^FT0,340^A0N,200,200^FH\^FB1200,1,0,C,1^FD@partnumber^FS
        '''^FT0,410^A0N,60,60^FH\^FB1200,1,0,L,1^FDUsuario: @user^FS
        '''^FT0,530^A0N,60,60^FH\^FB1200,2,0,L,1^FDMotivo: @reason^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_QualityLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_QualityLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^BY3,3,70^FT560,90^BCN,,N,N^FD@partnumber^FS
        '''^FT160,70^A0N,70,60^FH\^FB550,1,0,L,1^FD@supplierpart^FS
        '''^FT160,140^A0N,70,60^FH\^FB880,1,0,L,1^FD@suppliername^FS
        '''^FO0,453^GB970,0,6^FS
        '''^FO3,151^GB363,0,6^FS
        '''^FT125,185^A0N,28,28^FH\^FDESTACION^FS
        '''^FT5,255^A0N,100,65^FH\^FB360,1,0,C,1^FD@warehouse^FS
        '''^FO3,267^GB363,0,6^FS
        '''^FT10,298^A0N,28,28^FH\^FB350,1,0,C,1^FDPUNTO DE USO^FS
        '''^FT10,353^A0N,68,50^FH\^FB350,1,0,C, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ZPL_ReceivingLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_ReceivingLabel", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
