'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Delta_ERP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajax_loader_gray_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajax_loader_gray_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property AppIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AppIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property APTIV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("APTIV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_down_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_right_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_up_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_low() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_low", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battery_low_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_low_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_front_open_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_front_open_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_front_open_hand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_front_open_hand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_open_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_open_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_arrow_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_arrow_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_valid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_valid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_white_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_white_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_white_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_white_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bullet_wrench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_wrench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property critical_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("critical_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property critical_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("critical_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddr_inside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddr_inside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddr_inside_wait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddr_inside_wait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddr_not_started() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddr_not_started", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddr_outside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddr_outside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddr_outside_wait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddr_outside_wait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddr_scanning_in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddr_scanning_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ddr_scanning_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ddr_scanning_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_package_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_package_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property excel_exports_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel_exports_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flag_flyaway_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_flyaway_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greater_equal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greater_equal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property information_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property information_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property link_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minor_equal_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minor_equal_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property No_image_available() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_image_available", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property not_equal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("not_equal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property not_in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("not_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .auto-style2 {
        '''            color: #FFFFFF;
        '''            font-weight: bold;
        '''            background-color: #006699;
        '''        }
        '''    &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;h1 style=&quot;color: #5e9ca0;&quot;&gt;Mover de muestras&amp;nbsp;&lt;span style=&quot;color: #2b2301;&quot;&gt;@id&lt;/span&gt; aprobado.&lt;/h1&gt;
        '''&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;Detalles:&lt;/h2&gt;
        '''&lt;p&gt;&lt;strong&gt;Usuario:&lt;/strong&gt; @use [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ORD_MoverEmailTemplate() As String
            Get
                Return ResourceManager.GetString("ORD_MoverEmailTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date] AS DeliveryDate,CASE WHEN DATEPART(WEEKDAY,SC.Date) IN ({0},{1}) THEN 0 ELSE FLOOR(ISNULL(OpenQuantity,0)/{2}) END AS OpenQuantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board LEFT OUTER JOIN vw_Sch_WeeklyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Week] = CR.[Week] 
        '''WHERE ((&apos;{3}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_AverageRequirementsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_AverageRequirementsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date] AS DeliveryDate,CASE WHEN DATEPART(WEEKDAY,SC.Date) IN ({0},{1}) THEN 0 ELSE FLOOR(ISNULL(OpenQuantity,0)/{2}) END AS OpenQuantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board LEFT OUTER JOIN vw_Sch_WeeklyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Week] = CR.[Week] 
        '''INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''WHE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_AverageRequirementsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_AverageRequirementsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(SC.WorkingShifts,&apos;&apos;) AS DayShifts,B.ShiftCombination AS BoardShifts,CL.Seconds
        '''FROM Sys_Calendar AS SC
        '''LEFT OUTER JOIN Sys_ShiftCombination AS SF ON SC.WorkingShifts = SF.Combination
        '''CROSS JOIN Sch_Materials AS M  
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material
        '''INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board
        '''INNER JOIN Eng_1719Controls AS CL ON M.Material = CL.Material
        '''INNER JOIN Sys_ShiftCombination AS SFB ON B.ShiftCombination = SFB.Comb [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_BoardCapacitiesByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_BoardCapacitiesByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(SC.WorkingShifts,&apos;&apos;) AS DayShifts,Bd.ShiftCombination AS BoardShifts,CL.Seconds
        '''FROM Sys_Calendar AS SC
        '''LEFT OUTER JOIN Sys_ShiftCombination AS SF ON SC.WorkingShifts = SF.Combination
        '''CROSS JOIN Sch_Materials AS M  
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material
        '''INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board
        '''INNER JOIN Eng_1719Controls AS CL ON M.Material = CL.Material
        '''INNER JOIN Sys_ShiftCombination AS SFB ON Bd.ShiftCombination = SFB. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_BoardCapacitiesByFamily() As String
            Get
                Return ResourceManager.GetString("PP_BoardCapacitiesByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,SC.[Date],DATENAME(W,SC.[Date]) AS WeekDay,ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND M.Business = &apos;{2}&apos; 
        '''AND ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1} [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_ByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_ByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,SC.[Date],DATENAME(W,SC.[Date]) AS WeekDay,ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND B.Family = &apos;{2}&apos; 
        '''AND ((&apos; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_ByFamily() As String
            Get
                Return ResourceManager.GetString("PP_ByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,C.Comment 
        '''FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board INNER JOIN Sch_DailyProductionPlanComments AS C ON M.Material = C.Material AND MB.Board = C.Board WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction))
        '''AND M.Business = &apos;{2}&apos; AND B.Volume=&apos;Low&apos; ORDER BY M.Material.
        '''</summary>
        Friend ReadOnly Property PP_CommentsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_CommentsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,C.Comment 
        '''FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_DailyProductionPlanComments AS C ON M.Material = C.Material AND MB.Board = C.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction))
        '''AND B.Family = &apos;{2}&apos; AND Bd.Volume=&apos;Low&apos; 
        '''ORDER BY M.Material.
        '''</summary>
        Friend ReadOnly Property PP_CommentsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_CommentsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,Bd.Board,SC.[Date],DATENAME(W,SC.[Date]) AS WeekDay,ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS Bd ON M.Material = Bd.Material 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; 
        '''AND ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction))
        '''ORDER BY M.Material,SC.[Date].
        '''</summary>
        Friend ReadOnly Property PP_Daily_Plant() As String
            Get
                Return ResourceManager.GetString("PP_Daily_Plant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board 
        '''LEFT OUTER JOIN vw_Sch_EPSDailyProduction AS DP ON M.Material = DP.Material AND SC.[Date] = DP.[Date]
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) AND SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND M.Business = &apos;{2} [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_EPSProductionByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_EPSProductionByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date],ISNULL(Quantity,0) AS Quantity  
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''LEFT OUTER JOIN vw_Sch_EPSDailyProduction AS DP ON M.Material = DP.Material AND SC.[Date] = DP.[Date] 
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_EPSProductionByFamily() As String
            Get
                Return ResourceManager.GetString("PP_EPSProductionByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,Bd.Class AS Tool, Bd.Volume,Bd.ShiftCombination,Seconds,Operators,M.CustomerPN,M.Description,B.Family,M.Business,StdPack,ISNULL(PastDue,0) AS PastDue,ISNULL(CI.Quantity,0) AS Stock,StartProduction,EndProduction FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board  INNER JOIN Eng_1719Controls AS Cl ON M.Material = Cl.Material INNER JOIN Sch_Business AS B ON M.Business = B.Business LEFT OUT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_MaterialsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_MaterialsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,M.Class,MB.Board,Bd.Class AS Tool,BD.Volume,Bd.ShiftCombination,Seconds,Operators,M.CustomerPN,M.Description,B.Family,M.Business,StdPack,ISNULL(PastDue,0) AS PastDue,ISNULL(CI.Quantity,0) AS Stock,StartProduction,EndProduction FROM Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board  INNER JOIN Eng_1719Controls AS Cl ON M.Material = Cl.Material INNER JOIN Sch_Business AS B ON M.Business = B.Business LEFT OUTE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_MaterialsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_MaterialsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,MB.Board,SC.[Date] AS DeliveryDate,ISNULL(OpenQuantity,0) AS OpenQuantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS B ON MB.Board = B.Board LEFT OUTER JOIN vw_Sch_DailyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Date] = CR.DeliveryDate
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) AND SC.[Date] BETWEEN &apos;{ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_RequirementsByBusiness() As String
            Get
                Return ResourceManager.GetString("PP_RequirementsByBusiness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,Bd.Board,SC.[Date] AS DeliveryDate,ISNULL(OpenQuantity,0) AS OpenQuantity  
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M INNER JOIN Sch_MaterialBoards AS MB ON M.Material = MB.Material INNER JOIN Mfg_Boards AS Bd ON MB.Board = Bd.Board INNER JOIN Sch_Business AS B ON M.Business = B.Business 
        '''LEFT OUTER JOIN vw_Sch_DailyCustomerRequirements AS CR ON M.Material = CR.Material AND SC.[Date] = CR.DeliveryDate 
        '''WHERE ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_RequirementsByFamily() As String
            Get
                Return ResourceManager.GetString("PP_RequirementsByFamily", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT M.Material,Bd.Board,[Week],ISNULL(Quantity,0) AS Quantity 
        '''FROM Sys_Calendar AS SC CROSS JOIN Sch_Materials AS M 
        '''INNER JOIN Sch_MaterialBoards AS Bd ON M.Material = Bd.Material INNER JOIN Mfg_Boards AS Mb ON Bd.Board = Mb.Board 
        '''LEFT OUTER JOIN Sch_DailyProductionPlan AS PP ON M.Material = PP.Material AND SC.[Date] = PP.[Date] 
        '''WHERE SC.[Date] BETWEEN &apos;{0}&apos; AND &apos;{1}&apos; AND ((&apos;{0}&apos; BETWEEN StartProduction AND EndProduction) OR (&apos;{1}&apos; BETWEEN StartProduction AND EndProduction)) AND MB.Volume=&apos;Low&apos;         ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PP_Weekly_Plant() As String
            Get
                Return ResourceManager.GetString("PP_Weekly_Plant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property purple_warning_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purple_warning_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property radioactivity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("radioactivity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;title&gt;&lt;/title&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .auto-style2 {
        '''            color: #FFFFFF;
        '''            font-weight: bold;
        '''            background-color: #006699;
        '''        }
        '''    &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;h1 style=&quot;color: #5e9ca0;&quot;&gt;Material enviado a tracker de pendientes de procesar.&lt;/h1&gt;
        '''&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;Detalles:&lt;/h2&gt;
        '''&lt;p&gt;&lt;strong&gt;Usuario: &lt;/strong&gt; @username&lt;br /&gt;&lt;br /&gt;&lt;s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REC_TrackerEmailTemplate() As String
            Get
                Return ResourceManager.GetString("REC_TrackerEmailTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property red_warning_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_warning_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property run_macros_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run_macros_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_blue_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_blue_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_list_bullets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_bullets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_light_blue_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_light_blue_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_red_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_red_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wrench_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrench_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA^LL0600^PW1200
        '''^FT800,100^A0N,60,50^FH\^FB1100,1,0,L,1^FDFOLIO: @folio^FS
        '''
        '''^FO3,151^GB363,120,60^FS
        '''^FT125,185^A0N,28,28^FH\^FR^FDPUNTO DE USO^FS
        '''^FT5,260^A0N,68,50FH\^FB360,1,0,C,1^FR^FD@service^FS
        '''^FT10,298^A0N,28,28^FH\^FB350,1,0,C,1^FDPESO NETO^FS
        '''^FT10,353^A0N,68,50^FH\^FB350,1,0,C,1^FD@weight^FS
        '''^FT10,388^A0N,28,28^FH\^FB350,1,0,C,1^FDCANTIDAD^FS
        '''^FT10,448^A0N,70,70^FH\^FB350,1,0,C,1^FD@qty @uom^FS
        '''^FO0,151^GB1175,310,6^FS
        '''^FT100,100^A0N,110,140^FH\^FD@api^FS
        '''
        '''^FO360,156^GB0,300,6^FS
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ZPL_APILabel() As String
            Get
                Return ResourceManager.GetString("ZPL_APILabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT0,160^A0N,140,80^FH\^FB1200,1,0,C,1^FD***MATERIAL CONTROLADO***^FS
        '''^FT0,340^A0N,200,200^FH\^FB1200,1,0,C,1^FD@partnumber^FS
        '''^FT0,520^A0N,140,80^FH\^FB1200,1,0,C,1^FD*************************************^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_ControlledLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_ControlledLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT0,160^A0N,140,140^FH\^FB1200,1,0,C,1^FD*** CRITICO ***^FS
        '''^FT0,340^A0N,200,200^FH\^FB1200,1,0,C,1^FD@partnumber^FS
        '''^FT0,410^A0N,60,60^FH\^FB1200,1,0,L,1^FDUsuario: @user^FS
        '''^FT0,470^A0N,60,60^FH\^FB1200,1,0,L,1^FDArea: @area^FS
        '''^FT0,590^A0N,60,60^FH\^FB1200,2,0,L,1^FDComentario: @comment^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_CriticalLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_CriticalLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA^LL0400^PW1800
        '''^FT10,70^A0N,50,50^FH\^FB550,1,0,L,1^FDCDD^FS
        '''^FT300,70^A0N,50,50^FH\^FB550,1,0,L,1^FDLocal Smk^FS
        '''^FT550,70^A0N,50,50^FH\^FB550,1,0,L,1^FDLocal Serie^FS
        '''^FT800,70^A0N,50,50^FH\^FB550,1,0,L,1^FDEstatus^FS
        '''^FT1100,70^A0N,50,50^FH\^FB550,1,0,L,1^FDSerie^FS
        '''^FT1500,70^A0N,50,50^FH\^FB550,1,0,L,1^FDNo. de Parte^FS
        '''@rows
        '''^FO5,10^GB0,580,3^FS
        '''^FO290,10^GB0,580,3^FS
        '''^FO540,10^GB0,580,3^FS
        '''^FO790,10^GB0,580,3^FS
        '''^FO1090,10^GB0,580,3^FS
        '''^FO1490,10^GB0,580,3^FS
        '''^FO1785,10^GB0,580,3^FS        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ZPL_DicPicklist_6Cols() As String
            Get
                Return ResourceManager.GetString("ZPL_DicPicklist_6Cols", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^FT10,@item70^A0N,60,50^FH\^FB550,1,0,L,1^FD@cdd^FS
        '''^FT300,@item70^A0N,60,50^FH\^FB550,1,0,L,1^FD@smk^FS
        '''^FT550,@item70^A0N,60,50^FH\^FB550,1,0,L,1^FD0@local^FS
        '''^FT800,@item70^A0N,60,50^FH\^FB550,1,0,L,1^FD@status^FS
        '''^FT1100,@item70^A0N,60,50^FH\^FB550,1,0,L,1^FD@serial^FS
        '''^FT1500,@item70^A0N,60,50^FH\^FB550,1,0,L,1^FD@np^FS.
        '''</summary>
        Friend ReadOnly Property ZPL_DicPicklist_6Cols_Row() As String
            Get
                Return ResourceManager.GetString("ZPL_DicPicklist_6Cols_Row", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^FT@item70,200^A0N,60,50^FWB^FB550,1,0,L,1^FD@cdd^FS
        '''^FT@item70,650^A0N,40,30^FWB^FB400,2,0,L,1^FD@smk^FS
        '''^FT@item70,920^A0N,60,50^FWB^FB550,1,0,L,1^FD@local^FS
        '''^FT@item70,1130^A0N,60,50^FWB^FB550,1,0,L,1^FD@status^FS
        '''^FT@item70,1540^A0N,60,50^FWB^FB550,1,0,L,1^FD@serial^FS
        '''^FT@item70,1780^A0N,60,50^FWB^FB550,1,0,L,1^FD@np^FS.
        '''</summary>
        Friend ReadOnly Property ZPL_DicPicklist_6Cols_Row_Vertical() As String
            Get
                Return ResourceManager.GetString("ZPL_DicPicklist_6Cols_Row_Vertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA^XB^LL2107^PW903^MTD^MNN
        '''^FT70,190^A0N,50,50^FWB^FB550,1,0,L,1^FDCDD^FS
        '''^FT70,650^A0N,50,50^FWB^FB550,1,0,L,1^FDLocal Smk^FS
        '''^FT70,920^A0N,50,50^FWB^FB550,1,0,L,1^FDLocal Serie^FS
        '''^FT70,1130^A0N,50,50^FWB^FB550,1,0,L,1^FDEstatus^FS
        '''^FT70,1540^A0N,50,50^FWB^FB550,1,0,L,1^FDSerie^FS
        '''^FT70,1780^A0N,50,50^FWB^FB550,1,0,L,1^FDNo. Parte^FS
        '''
        '''@rows
        '''
        '''^FO5,10^GB0,1780,3^FS
        '''^FO85,10^GB0,1780,3^FS
        '''^FO590,10^GB0,1780,3^FS
        '''^FO10,10^GB580,0,3^FS
        '''^FO10,220^GB580,0,3^FS
        '''^FO10,670^GB580,0,3^FS
        '''^FO10,950^GB [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ZPL_DicPicklist_6Cols_Vertical() As String
            Get
                Return ResourceManager.GetString("ZPL_DicPicklist_6Cols_Vertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA
        '''^FO20,20^GB1180,120,70^FS
        '''^FT20,190^A0N,80,80^FB1180,2,0,C,1^FR^FDETIQUETA DE ENLACE^FS
        '''^FT20,280^A0N,160,110^FB1180,1,0,C,1^FD@partnumber^FS
        '''^FT20,390^A0N,50,50^FB1180,2,0,C,1^FD@description^FS
        '''^BY3,3,104^FT280,490^BCN,,N,N^FD@serial^FS
        '''^FT20,625^A0N,70,70^FB1180,2,0,C,1^FD@serial^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_LinkLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_LinkLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA^LL0600^PW1200
        '''^FO0,5^GB1175,140,70^FS
        '''^FT250,140^A0N,155,200^FH\^FR^FDMASTER^FS
        '''^FO3,151^GB363,120,60^FS
        '''^FT125,185^A0N,28,28^FH\^FR^FDESTACION^FS
        '''^FT5,260^A0N,90,65^FH\^FB360,1,0,C,1^FR^FD@warehouse^FS
        '''^FT10,298^A0N,28,28^FH\^FB350,1,0,C,1^FDPUNTO DE USO^FS
        '''^FT10,353^A0N,68,50^FH\^FB350,1,0,C,1^FD@service^FS
        '''^FT10,388^A0N,28,28^FH\^FB350,1,0,C,1^FDCANTIDAD^FS
        '''^FT10,448^A0N,70,70^FH\^FB350,1,0,C,1^FD@qty @uom^FS
        '''^FT970,230^A0N,100,60^FH\^FB210,1,0,C,1^FD@legend^FS
        '''^FT1020,290^A0N,28,28^FH\^FD [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ZPL_MasterLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_MasterLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT350,120^A0N,90,90^FH\^FB800,1,0,R,1^FDMover ID @moverid^FS
        '''^FT0,340^A0N,200,200^FH\^FB1200,1,0,C,1^FD@partnumber^FS
        '''^FT20,430^A0N,80,80^FH\^FB1200,1,0,L,1^FDCantidad: @quantity @uom^FS
        '''^FT20,490^A0N,60,60^FH\^FB1200,1,0,L,1^FDLocal: @local^FS
        '''^BY4,4,104^FT20,150^BCN,,Y,N^FD@partid^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_MoverLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_MoverLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH0,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT50,100^FB1100,1,0,C,0^A0N,70,60^FH\^FDMaterial^FS
        '''^FT50,200^FB1100,1,0,C,0^A0N,150,140^FH\^FD@partnumber^FS
        '''^FT50,520^FB1100,2,0,C,0^A0N,180,170^FH\^FDNO SURTIDO^FS
        '''^FT50,550^FB1100,2,0,C,0^A0N,80,80^FH\^FD@date^FS
        '''^FT100,540^FB1000,1,0,R,0^A0N,40,40^FH\^FDSMS Barriles^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_NoMaterial() As String
            Get
                Return ResourceManager.GetString("ZPL_NoMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA~TA000~JSN^LT0^MMT^MNW^MTT^PON^PMN^LH20,0^JMA^PR4,4^MD0^JUS^LRN^CI0^XZ^XA^LL0600^PW1200
        '''^FT0,160^A0N,140,100^FH\^FB1200,1,0,C,1^FD***ALERTA DE CALIDAD***^FS
        '''^FT0,340^A0N,200,200^FH\^FB1200,1,0,C,1^FD@partnumber^FS
        '''^FT0,410^A0N,60,60^FH\^FB1200,1,0,L,1^FDUsuario: @user^FS
        '''^FT0,530^A0N,60,60^FH\^FB1200,2,0,L,1^FDMotivo: @reason^FS
        '''^PQ1,0,1,Y^XZ.
        '''</summary>
        Friend ReadOnly Property ZPL_QualityLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_QualityLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^XA^LL0600^PW1200
        '''^BY3,3,70^FT700,90^BCN,,N,N^FD@partnumber^FS
        '''^FT160,70^A0N,70,60^FH\^FB550,1,0,L,1^FD@supplierpart^FS
        '''^FT160,140^A0N,60,50^FH\^FB1100,1,0,L,1^FD@suppliername^FS
        '''
        '''^FO3,151^GB363,120,60^FS
        '''^FT125,185^A0N,28,28^FH\^FR^FDESTACION^FS
        '''^FT5,260^A0N,90,65^FH\^FB360,1,0,C,1^FR^FD@warehouse^FS
        '''^FT10,298^A0N,28,28^FH\^FB350,1,0,C,1^FDPUNTO DE USO^FS
        '''^FT10,353^A0N,68,50^FH\^FB350,1,0,C,1^FD@service^FS
        '''^FT10,388^A0N,28,28^FH\^FB350,1,0,C,1^FDCANTIDAD^FS
        '''^FT10,448^A0N,70,70^FH\^FB350,1,0,C,1^ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ZPL_ReceivingLabel() As String
            Get
                Return ResourceManager.GetString("ZPL_ReceivingLabel", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
