Public Class Language
    'Primera posicion solo para guia
    Private Shared Sentences(,) As String = _
        {
            {0, "Find Next", "Buscar Siguiente"},
            {1, "Find Previous", "Buscar Anterior"},
            {2, "Find:", "Buscar:"},
            {3, "Match entire cell content", "Coincidir palabra completa"},
            {4, "Match case", "Coincidir MAYUSCULAS/minusculas"},
            {5, "Close", "Cerrar"},
            {6, "Find", "Buscar"},
            {7, "No matches found.", "No se encontraron coincidencias."},
            {8, "Cannot connect to server.", "Imposible conectar con el servidor."},
            {9, String.Format("Cannot connect to server, repair the internet connection.{0}Click OK to retry.", vbCrLf), String.Format("No es posible conectar con el servidor, repare la conexion a internet.{0}Clic en OK para reeintentar.", vbCrLf)},
            {10, String.Format("Cannot connect to server, repair the internet connection.{0}Do you want to retry?.", vbCrLf), String.Format("No es posible conectar con el servidor, repare la conexion a internet.{0}Deseas reintentar?.", vbCrLf)},
            {11, "No open connection.", "Ninguna conexion abierta."},
            {12, String.Format("Retrieving data error.{0}To detailed error press YES.", vbCrLf), String.Format("Error recuperando los datos.{0}Para ver los detalles presiona SI.", vbCrLf)},
            {13, "Detailed error.", "Error detallado."},
            {14, "Error adding data.", "Error al agregar los datos."},
            {15, String.Format("Changes not saved, there's a data error.{0}To detailed error press YES.", vbCrLf), String.Format("Cambios no guardados, existe un error en la información.{0}Para ver los detalles presiona SI.", vbCrLf)},
            {16, "No default printer found.", "No se encontró ninguna impresora predeterminada."},
            {17, "Set as default printer?", "Establecer como impresora determinada?"},
            {18, "Could not print.", "No fue posible imprimir."},
            {19, "COM port printing error.", "Error al imprimir en el puerto COM."},
            {20, "Printing error on IP: ", "Error al imprimir en la IP: "},
            {21, "Select sheet: ", "Seleccionar hoja: "},
            {22, "Loading file error.", "Ocurrio un error mientras se cargaba el archivo."},
            {23, "Save as...", "Guardar como..."},
            {24, "Page {0} of ", "Pagina {0} de "},
            {25, "Export Optiones", "Opciones de Exportacion"},
            {26, "Choose a format...", "Elige un formato..."},
            {27, "&CSV File", "Archivo &CSV"},
            {28, "&PDF File", "Archivo &PDF"},
            {29, "All", "Todo"},
            {30, "{0} records.", "{0} registros."},
            {31, "Saved!", "Guardado"},
            {32, "Copiado!", "Copiado!"},
            {33, "Save changes before close?", "Guardar cambios antes de cerrar?"},
            {34, "Error on saving.", "Error al guardar."},
            {35, "Changes not saved.", "Cambios no guardados."},
            {36, "Deleted!", "Eliminado!"},
            {37, "Pasted: changes not saved.", "Pegado: cambios sin guardar."},
            {38, "Error on pasting.", "Error al pegar."},
            {39, "New query: ", "Nueva consulta: "},
            {40, "SQL Editor", "Editor SQL"},
            {41, "Error on column '{0}', row {1}.{2}Clic YES to details.", "Error en columna '{0}', renglon {1}.{2}Para ver los detalles presiona SI."},
            {42, "Exception", "Excepcion"},
            {43, "Done!", "¡Hecho!"},
            {44, "Replace duplicates and insert new records on database?", "Reemplazar duplicados e insertar registros nuevos a la base de datos?"},
            {45, "Update", "Actualizar"},
            {46, "Imported: changes saved.", "Importado: cambios guardados."},
            {47, "Error on importing.", "Error al importar."},
            {48, "Imported: changes not saved.", "Importado: cambios no guardados."},
            {49, "Options", "Opciones"},
            {50, "&Print", "Im&primir"},
            {51, "&Export", "&Exportar"},
            {52, "&Import", "&Importar"},
            {53, "&Save", "&Guardar"},
            {54, "&Delete", "E&liminar"},
            {55, "&Copy", "&Copiar"},
            {56, "Pas&te", "Pe&gar"},
            {57, "&Find", "&Buscar"},
            {58, "Table:", "Tabla:"},
            {59, "Advanced mode", "Modo avanzado"},
            {60, "&Run", "Ejecuta&r"},
            {61, "Database Editor", "Editor de Base de Datos"},
            {62, "Clear filters", "Quitar filtros"},
            {63, "Sort A to Z", "Ordenar de A a Z"},
            {64, "Sort Z to A", "Ordenar de Z a A"},
            {65, "Clear filters from", "Quitar filtros de"},
            {66, "Text filter", "Filtro de texto"},
            {67, "Value filter", "Filtro por valor"},
            {68, "Hide column", "Ocultar columna"},
            {69, "(All)", "(Todo)"},
            {70, "(Null)", "(Nulo)"},
            {71, "Search...", "Buscar..."},
            {72, "Containers available reached minimum ({0} of {1}).", "Los contenedores disponibles son menores al minimo ({0} de {1})."},
            {73, "Minimum", "Minimo"},
            {74, "Last container declared empty ({0} {1} {2}).", "Ultimo contenedor declarado vacio ({0} {1} {2})."},
            {75, "Critical", "Critico"},
            {76, "{0} critical: last container declared empty.", "{0} critico: Ultimo contenedor declarado vacio."},
            {77, "{0} minimum reached: {1} container(s) available.", "{0} minimo alcanzado: {1} contenedor(es) disponible(s)."},
            {78, "Containers available reached maximum ({0} of {1}).", "Los contenedores disponibles sobrepasaron el maximo ({0} de {1})."},
            {79, "Maximum", "Maximo"},
            {80, "{0} maximum reached: {1} containers available.", "{0} maximo alcanzado: {1} contenedores disponibles."},
            {81, "({0}) Alerts", "({0}) Alertas"},
            {82, "Delta Notification", "Notificacion Delta"},
            {83, "No Alerts.", "Sin Alertas"},
            {84, "Any die center assigned.", "Ningun centro de dados asignado."},
            {85, "No authorized Checkpoint.", "Checkpoint no autorizado."},
            {86, "Session timeout expired!", "Tiempo de sesion expirado!"},
            {87, "Session closed", "Sesion terminada."},
            {88, "About...", "Acerca de..."},
            {89, "My Account", "Mi Cuenta"},
            {90, "Process Engineering", "Ingenieria de Proceso"},
            {91, "Scheduling", "Control de Producción"},
            {92, "Receiving", "Recibos"},
            {93, "Quality", "Calidad"},
            {94, "Ordering", "Ordenamiento"},
            {95, "Customer Service", "Servicio al Cliente"},
            {96, "Supermarket", "Supermercado"},
            {97, "Die Center", "Centro de Dados"},
            {98, "Component Delivery Routes", "Rutas de Componentes"},
            {99, "Leadprep", "Leadprep"},
            {100, "Secondary Leadprep", "Leadprep Secundarios"},
            {101, "Manufacturing", "Manufactura"},
            {102, "Finish Good Routes", "Rutas de Producto Terminado"},
            {103, "Shipping", "Embarques"},
            {104, "Material Analyst", "Analista de Materiales"},
            {105, "Administrator", "Administrador"},
            {106, "Start", "Inicio"},
            {107, "Profile", "Perfil"},
            {108, "Vacations", "Vacaciones"},
            {109, "Password", "Contraseña"},
            {110, "Language", "Idioma"},
            {111, "Spanish", "Español"},
            {112, "English", "Ingles"},
            {113, "Database", "Base de Datos"},
            {114, "Leadcodes", "Codigos L"},
            {115, "Raw Material", "Materia Prima"},
            {116, "Cutters", "Cortadoras"},
            {117, "Bill of Material", "Lista de Material"},
            {118, "Others", "Otros"},
            {119, "Reports", "Reportes"},
            {120, "Database errors", "Errores en BD"},
            {121, "Cutters Workload", "Carga de Cortadoras"},
            {122, "Database", "Base de Datos"},
            {123, "MRP Controllers", "MRP Controllers"},
            {124, "Families", "Familias"},
            {125, "Business", "Negocios"},
            {126, "Material Numbers", "Numeros de Parte"},
            {127, "Boards", "Tableros"},
            {128, "Material - Board", "Numeros de Parte - Tableros"},
            {129, "17/19 Controls", "Controles 17/19"},
            {130, "Headcount", "Personal"},
            {131, "Contracted Capacity", "Capacidad Contratada"},
            {132, "Shipping Days", "Dias de Embarque"},
            {133, "SAP", "SAP"},
            {134, "Import VL10", "Importar VL10"},
            {135, "Import ZMDESNR", "Importar ZMDESNR"},
            {136, "Import Inventory", "Importar Inventario"},
            {137, "Export Production Plan (CSV)", "Exportar Plan de Producción (CSV)"},
            {138, "Import Production Plan", "Importar Plan de Producción"},
            {139, "Print Labels", "Impresion de Etiquetas"},
            {140, "EPS", "EPS"},
            {141, "Import...", "Importar...."},
            {142, "Production Plan", "Plan de Producción"},
            {143, "Low Volume", "Bajo Volumen"},
            {144, "High Volume", "Alto Volumen"},
            {145, "Reports", "Reportes"},
            {146, "VL10", "VL10"},
            {147, "Variations", "Variaciones"},
            {148, "Capacity", "Capacidad"},
            {149, "Headcount", "Gente"},
            {150, "Current", "Actual"},
            {151, "Waterfall", "Cascada"},
            {152, "Production Plan", "Plan de Producción"},
            {153, "Headcount", "Gente"},
            {154, "Waterfall", "Cascada"},
            {155, "Labeling", "Etiquetado"},
            {156, "Labels", "Etiquetas"},
            {157, "New...", "Nueva..."},
            {158, "Reprint", "Reimprimir"},
            {159, "Delete", "Eliminar"},
            {160, "Reports", "Reportes"},
            {161, "Scanned Vs MB51", "Escaneado Vs Pagado"},
            {162, "Scanned Vs Stored", "Escaneado Vs Almacenado"},
            {163, "History", "Historial"},
            {164, "Management", "Administracion"},
            {165, "Alerts", "Alertas"},
            {166, "Label Flags", "Banderas de Etiqueta"},
            {167, "Scanners", "Escáneres"},
            {168, "Alerts", "Alertas"},
            {169, "New...", "Nueva..."},
            {170, "Remove", "Eliminar"},
            {171, "Unlock Serialnumber", "Desbloquear Serie"},
            {172, "Reports", "Reportes"},
            {173, "History", "Historial"},
            {174, "Locked Serialnumbers", "Series Bloqueadas"},
            {175, "Supermarket", "Supermercado"},
            {176, "Material Mover", "Mover de Material"},
            {177, "New...", "Nuevo"},
            {178, "Cancel", "Cancelar"},
            {179, "Approve", "Aprobar"},
            {180, "Print", "Imprimir"},
            {181, "Receiving", "Recibos"},
            {182, "Report Critical", "Reportar Critico"},
            {183, "Management", "Administracion"},
            {184, "MRP Controllers", "MRP Controllers"},
            {185, "Import Forecast", "Importar Pronostico..."},
            {186, "Reports", "Reportes"},
            {187, "MB51", "MB51"},
            {188, "261 Vs Z11", "261 Vs Z11"},
            {189, "Forecast", "Pronostico"},
            {190, "Forecast Vs Real Consumption", "Pronostico Vs Consumo Real"},
            {191, "Waterfall", "Cascada"},
            {192, "Material Mover", "Mover de Material"},
            {193, "History", "Historial"},
            {194, "ABC Analysis", "Analisis ABC"},
            {195, "Tools", "Herramientas"},
            {196, "SAP", "SAP"},
            {197, "VA32", "VA32"},
            {198, "Components", "Componentes"},
            {199, "Store", "Alta"},
            {200, "Open", "Abrir"},
            {201, "Location Change", "Cambio de Local"},
            {202, "Partial Discount", "Descuento Parcial"},
            {203, "Declare Empty", "Declarar Vacio"},
            {204, "Reactive Serialnumber", "Reactivar Serie"},
            {205, "Find", "Buscar"},
            {206, "Manual Adjustment", "Ajuste Manual"},
            {207, "Material Mover", "Mover de Material"},
            {208, "Print", "Imprimir"},
            {209, "Pick up", "Surtir"},
            {210, "Management", "Administracion"},
            {211, "SAP Post Transfers", "Transferencias a SAP"},
            {212, "Material Master", "Maestro de Materiales"},
            {213, "Supermarket Map", "Mapa de Supermercado"},
            {214, "Operators", "Operadores"},
            {215, "Reports", "Reportes"},
            {216, "SAP Vs Delta", "SAP Vs Delta"},
            {217, "Time Susceptible Material", "Material Susceptible al Tiempo"},
            {218, "Broken FIFO", "FIFO Roto"},
            {219, "Audit", "Auditoria"},
            {220, "Checkpoint Picklist", "Checkpoint de Surtido"},
            {221, "Print Picklist", "Imprimir Lista de Surtido"},
            {222, "Management", "Administracion"},
            {223, "Locations", "Mapa de CDD"},
            {224, "Centers", "Centros de Dados"},
            {225, "Checkpoints", "Checkpoints"},
            {226, "Checkpoint", "Checkpoint de Entrada"},
            {227, "Database", "Base de Datos"},
            {228, "Containerization", "Contenerizacion"},
            {229, "Engineering", "Ingenieria"},
            {230, "Production Control", "Control de Producción"},
            {231, "Business", "Negocios"},
            {232, "Kanbans", "Tarjetas Kanban"},
            {233, "Management", "Administracion"},
            {234, "Kanbans", "Generar Tarjetas Kanban"},
            {235, "Routes", "Rutas de Entrega"},
            {236, "Print", "Imprimir Tarjetas Kanban"},
            {237, "Workload", "Carga de Trabajo"},
            {238, "Operators", "Operadores"},
            {239, "Checkpoints", "Checkpoints"},
            {240, "Reports", "Reportes"},
            {241, "Engineering Vs ZCS12", "Ingenieria Vs ZCS12"},
            {242, "Miscellaneous", "Miscelaneos"},
            {243, "Bag Labels", "Etiquetas de Bolsas"},
            {244, "Checkpoint", "Checkpoint de Entrada"},
            {245, "Management", "Administracion"},
            {246, "Checkpoints", "Checkpoints"},
            {247, "Operators", "Operadores"},
            {248, "Routes", "Rutas"},
            {249, "Backflush", "Backflush"},
            {250, "Material Mover", "Mover de Material"},
            {251, "Ship", "Embarcar"},
            {252, "SAP", "SAP"},
            {253, "MB51", "MB51"},
            {254, "Reports", "Reportes"},
            {255, "MB51", "MB51"},
            {256, "WIP Monitoring", "Monitoreo WIP"},
            {257, "Database", "Base de Datos"},
            {258, "Working Dates", "Dias Habiles"},
            {259, "Parameters", "Parametros"},
            {260, "Raw Material", "Materia Prima"},
            {261, "Update", "Actualizar"},
            {262, "Users", "Usuarios"},
            {263, "Management", "Administracion"},
            {264, "Permissions", "Permisos"},
            {265, "Clone From...", "Clonar desde..."},
            {266, "Get New Password", "Nueva Contraseña"},
            {267, "SAP session not found.", "Sesion de SAP no encontrada."},
            {268, "", ""},
            {269, "", ""},
            {270, "", ""},
            {271, "", ""},
            {272, "", ""},
            {273, "", ""},
            {274, "", ""},
            {275, "", ""},
            {276, "", ""},
            {277, "", ""},
            {278, "", ""},
            {279, "", ""},
            {280, "", ""},
            {281, "", ""},
            {282, "", ""},
            {283, "", ""},
            {284, "", ""},
            {285, "", ""},
            {286, "", ""},
            {287, "", ""},
            {288, "", ""},
            {289, "", ""},
            {290, "", ""},
            {291, "", ""},
            {292, "", ""},
            {293, "", ""},
            {294, "", ""},
            {295, "", ""},
            {296, "", ""},
            {297, "", ""},
            {298, "", ""},
            {299, "", ""},
            {300, "", ""},
            {301, "", ""},
            {302, "", ""},
            {303, "", ""},
            {304, "", ""},
            {305, "", ""},
            {306, "", ""},
            {307, "", ""},
            {308, "", ""},
            {309, "", ""},
            {310, "", ""},
            {311, "", ""}
        }
    Protected Friend Shared ReadOnly Property Sentence(ByVal index As Integer) As String
        Get
            Return IIf(User.Current.Language = "EN", Sentences(index, 1), Sentences(index, 2))
        End Get
    End Property
End Class
